/**
 * DATABASE DES TITRES - STITCH 2026
 */
const SONG_DATABASE = {
    '8090': [
        { "artist": "Indochine", "title": "L'Aventurier", "hints": [] },
        { "artist": "Vanessa Paradis", "title": "Joe le taxi", "hints": [] },
        { "artist": "France Gall", "title": "Ella, elle l'a", "hints": [] },
        { "artist": "Images", "title": "Les démons de minuit", "hints": [] },
        { "artist": "Peter et Sloane", "title": "Besoin de rien, envie de toi", "hints": [] },
        { "artist": "Jeanne Mas", "title": "Toute première fois", "hints": [] },
        { "artist": "Niagara", "title": "L'amour à la plage", "hints": [] },
        { "artist": "Lio", "title": "Amoureux solitaires", "hints": [] },
        { "artist": "Rose Laurens", "title": "Africa", "hints": [] },
        { "artist": "Hervé Cristiani", "title": "Il est libre Max", "hints": [] },
        { "artist": "Axel Bauer", "title": "Cargo", "hints": [] },
        { "artist": "Taxi Girl", "title": "Cherchez le garçon", "hints": [] },
        { "artist": "Les Rita Mitsouko", "title": "Marcia Baïla", "hints": [] },
        { "artist": "Partenaire Particulier", "title": "Partenaire particulier", "hints": [] },
        { "artist": "Jean-Jacques Goldman", "title": "Envole-moi", "hints": [] },
        { "artist": "Jean-Jacques Goldman", "title": "Je te donne", "hints": [] },
        { "artist": "Fredericks Goldman Jones", "title": "À nos actes manqués", "hints": [] },
        { "artist": "Téléphone", "title": "Cendrillon", "hints": [] },
        { "artist": "Téléphone", "title": "Ça (c'est vraiment toi)", "hints": [] },
        { "artist": "Bandolero", "title": "Paris Latino", "hints": [] },
        { "artist": "Jean Schultheis", "title": "Confidence pour confidence", "hints": [] },
        { "artist": "Thierry Pastor", "title": "Le coup de folie", "hints": [] },
        { "artist": "Jean-Luc Lahaye", "title": "Femme que j'aime", "hints": [] },
        { "artist": "François Valéry", "title": "Aimons-nous vivants", "hints": [] },
        { "artist": "Philippe Cataldo", "title": "Les Divas du dancing", "hints": [] },
        { "artist": "Les Avions", "title": "Nuit sauvage", "hints": [] },
        { "artist": "Jakie Quartz", "title": "Mise au point", "hints": [] },
        { "artist": "Caroline Loeb", "title": "C'est la ouate", "hints": [] },
        { "artist": "Jacques Higelin", "title": "Tombé du ciel", "hints": [] },
        { "artist": "Mylène Farmer", "title": "Désenchantée", "hints": [] },
        { "artist": "Céline Dion", "title": "Pour que tu m'aimes encore", "hints": [] },
        { "artist": "Céline Dion & Jean-Jacques Goldman", "title": "J'irai où tu iras", "hints": [] },
        { "artist": "Fredericks Goldman Jones", "title": "Né en 17 à Leidenstadt", "hints": [] },
        { "artist": "MC Solaar", "title": "Caroline", "hints": [] },
        { "artist": "MC Solaar", "title": "Bouge de là", "hints": [] },
        { "artist": "IAM", "title": "Je danse le mia", "hints": [] },
        { "artist": "Zebda", "title": "Tomber la chemise", "hints": [] },
        { "artist": "Tina Arena", "title": "Aller plus haut", "hints": [] },
        { "artist": "Pauline Ester", "title": "Oui je l'adore", "hints": [] },
        { "artist": "Roch Voisine", "title": "Hélène", "hints": [] },
        { "artist": "Roch Voisine", "title": "Pourtant", "hints": [] },
        { "artist": "Didier Barbelivien & Félix Gray", "title": "À toutes les filles", "hints": [] },
        { "artist": "Demis Roussos", "title": "On écrit sur les murs", "hints": [] },
        { "artist": "Johnny Hallyday", "title": "Je te promets", "hints": [] },
        { "artist": "Lagaf'", "title": "La zoubida", "hints": [] },
        { "artist": "Zouk Machine", "title": "Maldòn (la musique dans la peau)", "hints": [] },
        { "artist": "Pascal Obispo", "title": "Tomber pour elle", "hints": [] },
        { "artist": "Alain Souchon", "title": "Sous les jupes des filles", "hints": [] },
        { "artist": "Alain Bashung", "title": "Madame rêve", "hints": [] },
        { "artist": "Niagara", "title": "J'ai vu", "hints": [] },
        { "artist": "Laurent Voulzy", "title": "Les nuits sans Kim Wilde", "hints": [] },
        { "artist": "Axel Bauer", "title": "Éteins la lumière", "hints": [] },
        { "artist": "François Feldman", "title": "Les valses de Vienne", "hints": [] },
        { "artist": "Teri Moïse", "title": "Je serai là", "hints": [] },
        { "artist": "Mylène Farmer", "title": "Tomber...", "hints": [] },
        { "artist": "Hélène", "title": "Hélène et les garçons", "hints": [] },
        { "artist": "Marc Lavoine", "title": "Tomber la nuit", "hints": [] }
    ],
    'raphaly': [
        { artist: 'Ninho', title: 'Mamacita', hints: ["Gazo", "Damso", "Tiakola", "SDM"] },
        { artist: 'Ninho', title: 'Elle m\'a eu', hints: ["Jul", "SCH", "SDM", "Gazo"] },
        { artist: 'Ninho', title: 'Jefe', hints: ["Damso", "Tiakola", "Gazo", "SDM"] },
        { artist: 'Ninho', title: 'VVS', hints: ["Tiakola", "Gazo", "SDM", "Hamza"] },
        { artist: 'Ninho', title: 'Lettre à une femme', hints: ["Gazo", "Tiakola", "Jul", "Naps"] },
        { artist: 'PNL', title: 'Menace', hints: ["DTF", "Ademo", "N.O.S", "Ziak"] },
        { artist: 'PNL', title: 'Au DD', hints: ["DTF", "Ademo", "N.O.S", "Tarik"] },
        { artist: 'Hamza', title: 'Fade Up', hints: ["SCH", "Zola", "SDM", "Gazo"] },
        { artist: 'Hamza', title: 'Kyky2Bondy', hints: ["SCH", "Zola", "SDM", "Gazo"] },
        { artist: 'Dadju', title: 'Bob Marley', hints: ["Gims", "Tayc", "Franglish", "Ninho"] },
        { artist: 'Zola', title: 'Amber', hints: ["Gazo", "Koba LaD", "Maes", "Ninho"] },
        { artist: 'Aya Nakamura', title: 'Baddies', hints: ["Gazo", "Tiakola", "Hamza", "SDM"] },
        { artist: 'Aya Nakamura', title: 'Djadja', hints: ["Ronisia", "Wejdene", "Tayc", "Tiakola"] },
        { artist: 'Aya Nakamura', title: 'Pookie', hints: ["Ronisia", "Imen Es", "Dadju", "Gazo"] },
        { artist: 'Jul', title: 'Madame', hints: ["Jul", "SCH", "Naps", "Alonzo"] },
        { artist: 'Jul', title: 'Tchikita', hints: ["Naps", "Alonzo", "Soso Maness", "Jul"] },
        { artist: 'Orelsan', title: 'La Quête', hints: ["Vald", "Lomepal", "Nekfeu", "Damso"] },
        { artist: 'SDM', title: 'Pour Elle', hints: ["Gazo", "Tiakola", "Ninho", "SDM"] },
        { artist: 'SDM', title: 'Bolide Allemand', hints: ["Gazo", "Tiakola", "Ninho", "Werenoi"] },
        { artist: 'Gazo', title: 'DIE', hints: ["Central Cee", "Zola", "Koba LaD", "Gazo"] },
        { artist: 'Gazo', title: 'Celine 3X', hints: ["Tiakola", "SDM", "Ninho", "Hamza"] },
        { artist: 'Tiakola', title: 'Meuda', hints: ["Niska", "Hamza", "Gazo", "Tiakola"] },
        { artist: 'Tiakola', title: 'Gasolina', hints: ["Gazo", "Niska", "SDM", "Hamza"] },
        { artist: 'Naps', title: 'La Kiffance', hints: ["Jul", "Soso Maness", "L'Algérino", "Naps"] },
        { artist: 'SCH', title: 'Bande Organisée', hints: ["Jul", "Naps", "Soso Maness", "Alonzo"] },
        { artist: 'SCH', title: 'Otto', hints: ["Jul", "Naps", "Soso Maness", "SCH"] },
        { artist: 'PLK', title: 'Petrouchka', hints: ["Soso Maness", "Oboy", "Zola", "PLK"] },
        { artist: 'Tayc', title: 'Le Temps', hints: ["Dadju", "Burnaboy", "Wizkid", "Tayc"] },
        { artist: 'Werenoi', title: 'Pyramide', hints: ["Ninho", "SDM", "Damso", "Tiakola"] },
        { artist: 'Heuss L\'enfoiré', title: 'Moulaga', hints: ["Jul", "Naps", "Soso Maness", "Alonzo"] },
        { artist: 'Black M', title: 'Sur ma route', hints: ["Sexion d'Assaut", "Maître Gims", "Lefa", "Maska"] },
        { artist: 'Kaaris', title: 'Or noir', hints: ["Booba", "Niro", "Gradur", "Lacrim"] },
        { artist: 'Lacrim', title: 'A7', hints: ["SCH", "Kaaris", "Booba", "Ninho"] },
        { artist: 'Booba', title: 'Mona Lisa', hints: ["SDM", "Ninho", "Tiakola", "Gazo"] }
    ],
    'grungerock': [
        { artist: "K's Choice", title: "Not an Addict", hints: [] },
        { artist: "The Cranberries", title: "Zombie", hints: [] },
        { artist: "Garbage", title: "Stupid Girl", hints: [] },
        { artist: "Skunk Anansie", title: "Infidelity (Only You)", hints: [] },
        { artist: "Silverchair", title: "Tomorrow", hints: [] },
        { artist: "Nirvana", title: "Something In The Way", hints: [] },
        { artist: "Red Hot Chili Peppers", title: "Under the Bridge", hints: [] },
        { artist: "U2", title: "With or Without You", hints: [] },
        { artist: "The Police", title: "Roxanne", hints: [] },
        { artist: "No Doubt", title: "Don't Speak", hints: [] },
        { artist: "INXS", title: "Need You Tonight", hints: [] },
        { artist: "Led Zeppelin", title: "Whole Lotta Love", hints: [] },
        { artist: "Queen", title: "Bohemian Rhapsody", hints: [] },
        { artist: "Soundgarden", title: "Black Hole Sun", hints: [] },
        { artist: "Green Day", title: "Basket Case", hints: [] },
        { artist: "Beck", title: "Loser", hints: [] },
        { artist: "Oasis", title: "Wonderwall", hints: [] },
        { artist: "Sheryl Crow", title: "All I Wanna Do", hints: [] },
        { artist: "Spin Doctors", title: "Two Princes", hints: [] },
        { artist: "Radiohead", title: "Creep", hints: [] },
        { artist: "Rage Against the Machine", title: "Bulls On Parade", hints: [] },
        { artist: "Counting Crows", title: "Mr. Jones", hints: [] },
        { artist: "Blur", title: "Song 2", hints: [] },
        { artist: "The Smashing Pumpkins", title: "Bullet With Butterfly Wings", hints: [] },
        { artist: "Red Hot Chili Peppers", title: "Give It Away", hints: [] },
        { artist: "Lenny Kravitz", title: "Are You Gonna Go My Way", hints: [] },
        { artist: "Weezer", title: "Say It Ain't So", hints: [] },
        { artist: "Collective Soul", title: "Shine", hints: [] },
        { artist: "The Breeders", title: "Cannonball", hints: [] },
        { artist: "Beck", title: "Where It's At", hints: [] },
        { artist: "Aerosmith", title: "Crazy", hints: [] },
        { artist: "Weezer", title: "Buddy Holly", hints: [] },
        { artist: "Last Train", title: "Scars", hints: [] }
    ],
    'disney': [
        { brand: 'Le Roi Lion', artist: 'Debbie Davis', title: 'L\'histoire de la vie' },
        { brand: 'Le Roi Lion', artist: 'Emmanuel Curtil', title: 'Je voudrais déjà être roi' },
        { brand: 'Le Roi Lion', artist: 'Emmanuel Curtil', title: 'Hakuna Matata' },
        { brand: 'Le Roi Lion', artist: 'Maeva Méline', title: 'L\'amour brille sous les étoiles' },
        { brand: 'Aladdin', artist: 'Paolo Domingo', title: 'Ce rêve bleu' },
        { brand: 'Aladdin', artist: 'Richard Darbois', title: 'Prince Ali' },
        { brand: 'Aladdin', artist: 'Richard Darbois', title: 'Je suis ton meilleur ami' },
        { brand: 'Aladdin', artist: 'Paolo Domingo', title: 'Nuits d\'Arabie' },
        { brand: 'La Petite Sirène', artist: 'Henri Salvador', title: 'Sous l\'océan' },
        { brand: 'La Petite Sirène', artist: 'Claire Guyot', title: 'Partir là-bas' },
        { brand: 'La Petite Sirène', artist: 'Gérard Rinaldi', title: 'Embrasse-la' },
        { brand: 'La Belle et la Bête', artist: 'Liane Foly', title: 'Histoire éternelle' },
        { brand: 'La Belle et la Bête', artist: 'Lucie Dolène', title: 'C\'est la fête' },
        { brand: 'La Belle et la Bête', artist: 'Bénédicte Lécroart', title: 'Belle' },
        { brand: 'Pocahontas', artist: 'Laura Mayne', title: 'L\'air du vent' },
        { brand: 'Pocahontas', artist: 'Karine Costa', title: 'Des sauvages' },
        { brand: 'Mulan', artist: 'Patrick Fiori', title: 'Comme un homme' },
        { brand: 'Mulan', artist: 'Marie Galey', title: 'Réflexion' },
        { brand: 'Hercule', artist: 'Emmanuel Dahl', title: 'De zéro en héros' },
        { brand: 'Hercule', artist: 'Mimi Félixine', title: 'Jamais je n\'avouerai' },
        { brand: 'Tarzan', artist: 'Phil Collins', title: 'Je veux savoir' },
        { brand: 'Tarzan', artist: 'Phil Collins', title: 'Entre deux mondes' },
        { brand: 'Toy Story', artist: 'Charlélie Couture', title: 'Je suis ton ami' },
        { brand: 'La Reine des Neiges', artist: 'Anaïs Delva', title: 'Libérée, délivrée' },
        { brand: 'La Reine des Neiges', artist: 'Emmylou Homs', title: 'Le renouveau' },
        { brand: 'Raiponce', artist: 'Maeva Méline', title: 'Où est la vraie vie ?' },
        { brand: 'Raiponce', artist: 'Maeva Méline', title: 'Je veux y croire' },
        { brand: 'Vaiana', artist: 'Cerise Calixte', title: 'Le Bleu lumière' },
        { brand: 'Vaiana', artist: 'Anthony Kavanagh', title: 'Pour les hommes' },
        { brand: 'Vaiana', artist: 'Jean-Luc Guizonne', title: 'L\'explorateur' },
        { brand: 'Le Livre de la Jungle', artist: 'Jean Stout', title: 'Il en faut peu pour être heureux' },
        { brand: 'Le Livre de la Jungle', artist: 'José Bartel', title: 'Être un homme comme vous' },
        { brand: 'Les Aristochats', artist: 'José Bartel', title: 'Tout le monde veut devenir un cat' },
        { brand: 'Robin des Bois', artist: 'Gilles Guillot', title: 'Quel beau jour vraiment' },
        { brand: 'Peter Pan', artist: 'Générique', title: 'Tu t\'envoles' },
        { brand: 'Pinocchio', artist: 'Générique', title: 'Quand on prie la bonne étoile' },
        { brand: 'Cendrillon', artist: 'Générique', title: 'Tendre rêve' },
        { brand: 'Blanche-Neige', artist: 'Générique', title: 'Un jour mon prince viendra' },
        { brand: 'La Princesse et la Grenouille', artist: 'China Moses', title: 'Au bout du rêve' },
        { brand: 'Mary Poppins', artist: 'Générique', title: 'Supercalifragilisticexpialidocious' },
        { brand: 'Les 101 Dalmatiens', artist: 'Générique', title: 'Cruella d\'Enfer' },
        { brand: 'Frère des Ours', artist: 'Phil Collins', title: 'Je m\'en vais' },
        { brand: 'Coco', artist: 'Andrea Santamaria', title: 'Ne m\'oublie pas' },
        { brand: 'Coco', artist: 'Andrea Santamaria', title: 'Un poco loco' },
        { brand: 'Encanto', artist: 'Générique', title: 'Ne parlons pas de Bruno' },
        { brand: 'Le Monde de Nemo', artist: 'Générique', title: 'Au-delà du récif' },
        { brand: 'Le Bossu de Notre-Dame', artist: 'Francis Lalanne', title: 'Rien qu\'un jour' },
        { brand: 'La Planète au Trésor', artist: 'David Hallyday', title: 'Un homme libre' },
        { brand: 'Frère des Ours', artist: 'Phil Collins', title: 'Regarde dans mes yeux' },
        { brand: 'Cars', artist: 'Rascal Flatts', title: 'Life is a Highway' }
    ],
    'rapfr': [
        { artist: 'Suprême NTM', title: 'La fièvre', hints: ["IAM", "Lunatic", "Fonky Family", "Assassin"] },
        { artist: 'Fonky Family', title: 'Mystère et suspense', hints: ["IAM", "Assassin", "Suprême NTM", "Ärsenik"] },
        { artist: 'Assassin', title: 'L\'odyssée suit son cours', hints: ["Suprême NTM", "IAM", "Ideal J", "Fonky Family"] },
        { artist: 'Oxmo Puccino ft. Dany Dan', title: 'A ton enterrement', hints: ["La Cliqua", "Lunatic", "Booba", "Kery James"] },
        { artist: 'Fabe ft. Dany Dan', title: 'Rien ne change à part les saisons', hints: ["Oxmo Puccino", "Doc Gynéco", "Rocé", "La Rumeur"] },
        { artist: 'Suprême NTM', title: 'Seine Saint Denis Style', hints: ["IAM", "Assassin", "Fonky Family", "Ideal J"] },
        { artist: 'Assassin', title: 'Shoota Babylone', hints: ["Suprême NTM", "IAM", "Ideal J", "X-Men"] },
        { artist: 'Tandem', title: 'Les maux', hints: ["La Rumeur", "La Cliqua", "Ärsenik", "Time Bomb"] },
        { artist: 'Daddy Lord C', title: 'Freaky flow', hints: ["Zoxea", "Rocca", "Casey", "Tandem"] },
        { artist: 'Akhenaton', title: 'Au fin fond d\'une contrée', hints: ["Suprême NTM", "IAM", "Fonky Family", "Booba"] },
        { artist: 'Kery James', title: '28 décembre 1977', hints: ["Oxmo Puccino", "Casey", "Ékoué", "Booba"] },
        { artist: 'Zoxea', title: 'Rap musique que j\'aime', hints: ["Daddy Lord C", "Rocca", "Casey", "La Cliqua"] },
        { artist: 'La Brigade ft. Lunatic', title: '16 rimes', hints: ["Fonky Family", "Ärsenik", "Suprême NTM", "Booba"] },
        { artist: 'Fabe', title: 'Aujourd\'hui', hints: ["Oxmo Puccino", "Doc Gynéco", "Kery James", "Rocé"] },
        { artist: 'Akhenaton ft. Fonky Family', title: 'Bad Boys de Marseille', hints: ["Suprême NTM", "IAM", "Ärsenik", "La Brigade"] },
        { artist: 'La Rumeur', title: 'La cuir usé d\'une valise', hints: ["Ärsenik", "Tandem", "La Cliqua", "Casey"] },
        { artist: 'Ideal J', title: 'Le ghetto français', hints: ["X-Men", "Assassin", "Suprême NTM", "IAM"] },
        { artist: 'Akhenaton', title: 'Mon texte le savon', hints: ["Suprême NTM", "IAM", "Fonky Family", "Booba"] },
        { artist: 'Lunatic ft. Jockey', title: 'Le silence n\'est pas un oubli', hints: ["La Brigade", "Booba", "La Cliqua", "Ärsenik"] },
        { artist: 'Doc Gynéco', title: 'L\'homme qui ne valait pas dix centimes', hints: ["Oxmo Puccino", "Fabe", "Kery James", "Rocé"] },
        { artist: 'Shurik\'N', title: 'Lettre', hints: ["Akhenaton", "Kery James", "Casey", "Ékoué"] },
        { artist: 'Casey', title: 'Chez moi', hints: ["Kery James", "Ékoué", "La Rumeur", "Assassin"] },
        { artist: 'Les Sages Poètes de la Rue', title: 'Qu\'est-ce qui fait marcher les sages', hints: ["La Cliqua", "Tandem", "Ärsenik", "Time Bomb"] },
        { artist: 'La Rumeur', title: 'L\'ombre sur la mesure', hints: ["Ärsenik", "Tandem", "La Cliqua", "Casey"] },
        { artist: 'Booba', title: 'Le bitume avec une plume', hints: ["Suprême NTM", "Lunatic", "La Brigade", "Ärsenik"] },
        { artist: 'Fonky Family', title: 'Sans rémission', hints: ["IAM", "Assassin", "Suprême NTM", "Ärsenik"] },
        { artist: 'Kery James', title: '2 issues', hints: ["Oxmo Puccino", "Casey", "Ékoué", "Booba"] },
        { artist: 'La Cliqua', title: 'Un dernier jour sur Terre', hints: ["Tandem", "Ärsenik", "La Rumeur", "Time Bomb"] },
        { artist: 'Fabe', title: 'Des durs, des boss... des dombis !', hints: ["Oxmo Puccino", "Doc Gynéco", "Kery James", "Rocé"] },
        { artist: 'Time Bomb', title: 'Les bidons veulent le guidon', hints: ["La Cliqua", "Ärsenik", "Tandem", "La Rumeur"] },
        { artist: 'Suprême NTM', title: 'Tout n\'est pas si facile', hints: ["IAM", "Assassin", "Fonky Family", "Ideal J"] },
        { artist: 'Rocé', title: 'On s\'habitue', hints: ["Doc Gynéco", "Fabe", "Kery James", "Casey"] },
        { artist: 'Doc Gynéco', title: 'Nirvana', hints: ["Oxmo Puccino", "Fabe", "Kery James", "Rocé"] },
        { artist: 'Rocca', title: 'Les jeunes de l\'univers', hints: ["Zoxea", "Daddy Lord C", "La Cliqua", "Tandem"] },
        { artist: 'Shurik\'N ft. Akhenaton', title: 'Manifeste', hints: ["Fonky Family", "IAM", "Fonky Family", "Booba"] },
        { artist: 'Ärsenik', title: 'Boxe avec les mots', hints: ["La Rumeur", "La Cliqua", "Tandem", "Time Bomb"] },
        { artist: 'Shurik\'N', title: 'Samouraï', hints: ["Akhenaton", "Kery James", "Casey", "Ékoué"] },
        { artist: 'Chiens de Paille', title: 'Comme un aimant', hints: ["La Rumeur", "Ärsenik", "Tandem", "La Cliqua"] },
        { artist: 'IAM', title: 'La fin de leur monde', hints: ["Suprême NTM", "Fonky Family", "Assassin", "Ärsenik"] },
        { artist: 'Lunatic', title: 'Civilisé', hints: ["Booba", "La Brigade", "Ärsenik", "La Cliqua"] },
        { artist: 'IAM', title: 'Nés sous la même étoile', hints: ["Suprême NTM", "Fonky Family", "Assassin", "Akhenaton"] },
        { artist: 'X-Men', title: 'Pendez-les, bandez-les, descendez-les', hints: ["Ideal J", "Assassin", "Suprême NTM", "IAM"] },
        { artist: 'Suprême NTM', title: 'Qu\'est-ce qu\'on attend ?', hints: ["IAM", "Assassin", "Fonky Family", "Booba"] },
        { artist: 'Fabe', title: 'L\'impertinent', hints: ["Oxmo Puccino", "Doc Gynéco", "Rocé", "La Rumeur"] },
        { artist: 'Booba', title: 'Ma définition', hints: ["Suprême NTM", "Lunatic", "La Brigade", "Ärsenik"] },
        { artist: 'Suprême NTM', title: 'Laisse pas traîner ton fils', hints: ["IAM", "Assassin", "Fonky Family", "Ideal J"] },
        { artist: 'Booba', title: 'Repose en paix', hints: ["Suprême NTM", "Lunatic", "La Brigade", "Ärsenik"] },
        { artist: 'Ékoué', title: 'Blessé dans mon égo', hints: ["Casey", "Kery James", "La Rumeur", "Assassin"] },
        { artist: 'Lunatic', title: 'la lettre', hints: ["Booba", "La Brigade", "Ärsenik", "La Cliqua"] },
        { artist: 'IAM', title: 'Petit frère', hints: ["Suprême NTM", "Fonky Family", "Assassin", "Akhenaton"] }
    ],
    'rapus': [
        { "artist": "TLC", "title": "No Scrubs", "hints": ["Destiny's Child", "Brandy", "Aaliyah", "SWV"] },
        { "artist": "Mario", "title": "Let Me Love You", "hints": ["Usher", "Ginuwine", "Akon", "Joe"] },
        { "artist": "Destiny's Child", "title": "Say My Name", "hints": ["TLC", "Brandy", "SWV", "En Vogue"] },
        { "artist": "Craig David", "title": "7 Days", "hints": ["Ne-Yo", "Akon", "Mario", "Usher"] },
        { "artist": "Busta Rhymes", "title": "I Know What You Want", "hints": ["Jay-Z", "Missy Elliott", "Nelly", "Ludacris"] },
        { "artist": "Michael Jackson", "title": "You Rock My World", "hints": ["Usher", "Chris Brown", "Beyoncé", "R. Kelly"] },
        { "artist": "Ciara", "title": "Like a Boy", "hints": ["Beyoncé", "Rihanna", "Ashanti", "Amerie"] },
        { "artist": "Usher", "title": "U Remind Me", "hints": ["Chris Brown", "Mario", "Ginuwine", "Akon"] },
        { "artist": "Brandy & Monica", "title": "The Boy Is Mine", "hints": ["TLC", "Destiny's Child", "SWV", "En Vogue"] },
        { "artist": "Blu Cantrell", "title": "Breathe", "hints": ["Ashanti", "Amerie", "Ciara", "Mýa"] },
        { "artist": "Alicia Keys", "title": "My Boo", "hints": ["Beyoncé", "Ciara", "Ashanti", "Mary J. Blige"] },
        { "artist": "Lauryn Hill", "title": "Doo Wop (That Thing)", "hints": ["Missy Elliott", "Mary J. Blige", "TLC", "SWV"] },
        { "artist": "B2K", "title": "Bump, Bump, Bump", "hints": ["Usher", "Chris Brown", "Mario", "Bow Wow"] },
        { "artist": "Akon", "title": "Lonely", "hints": ["Craig David", "Ne-Yo", "Mario", "Usher"] },
        { "artist": "Toni Braxton", "title": "He Wasn't Man Enough", "hints": ["Mary J. Blige", "Mariah Carey", "Whitney Houston", "Brandy"] },
        { "artist": "Fugees", "title": "Ready or Not", "hints": ["Busta Rhymes", "Wyclef Jean", "Lauryn Hill", "Jay-Z"] },
        { "artist": "Jennifer Lopez", "title": "Jenny from the Block", "hints": ["Beyoncé", "Ciara", "Ashanti", "Shakira"] },
        { "artist": "Alicia Keys", "title": "Fallin'", "hints": ["Beyoncé", "Mary J. Blige", "Mariah Carey", "Lauryn Hill"] },
        { "artist": "Rihanna", "title": "Umbrella", "hints": ["Beyoncé", "Ciara", "Amerie", "Ashanti"] },
        { "artist": "Blackstreet", "title": "No Diggity", "hints": ["Boyz II Men", "Next", "Ginuwine", "Usher"] },
        { "artist": "T-Pain", "title": "Buy U a Drank", "hints": ["Akon", "Ne-Yo", "Usher", "Lil Wayne"] },
        { "artist": "Chris Brown", "title": "With You", "hints": ["Usher", "Mario", "Bow Wow", "Ne-Yo"] },
        { "artist": "Craig David", "title": "Walking Away", "hints": ["Akon", "Ne-Yo", "Mario", "Usher"] },
        { "artist": "Sean Kingston", "title": "Beautiful Girls", "hints": ["Akon", "T-Pain", "Chris Brown", "Mario"] },
        { "artist": "R. Kelly", "title": "Ignition (Remix)", "hints": ["Usher", "Ginuwine", "Joe", "Tyrese"] },
        { "artist": "Shakira", "title": "Hips Don't Lie", "hints": ["Jennifer Lopez", "Ciara", "Beyoncé", "Rihanna"] },
        { "artist": "Brandy", "title": "Right Here (Departed)", "hints": ["Monica", "Ashanti", "Amerie", "Mýa"] },
        { "artist": "Cassidy", "title": "Hotel", "hints": ["Nelly", "Ludacris", "Busta Rhymes", "Jay-Z"] },
        { "artist": "Beyoncé", "title": "Crazy In Love", "hints": ["Rihanna", "Alicia Keys", "Ciara", "Ashanti"] },
        { "artist": "Wyclef Jean", "title": "911", "hints": ["Fugees", "Lauryn Hill", "Jay-Z", "Busta Rhymes"] },
        { "artist": "Joe", "title": "Ride Wit U", "hints": ["Ginuwine", "R. Kelly", "Tyrese", "Usher"] },
        { "artist": "Ginuwine", "title": "Pony", "hints": ["R. Kelly", "Joe", "Tyrese", "Usher"] },
        { "artist": "Nelly", "title": "Dilemma", "hints": ["Ludacris", "Busta Rhymes", "Jay-Z", "Cassidy"] },
        { "artist": "Whitney Houston", "title": "I Have Nothing", "hints": ["Mariah Carey", "Toni Braxton", "Mary J. Blige", "Brandy"] },
        { "artist": "Amerie", "title": "1 Thing", "hints": ["Ciara", "Rihanna", "Ashanti", "Mýa"] },
        { "artist": "Madcon", "title": "Beggin'", "hints": ["Akon", "Sean Kingston", "T-Pain", "Ne-Yo"] },
        { "artist": "Bow Wow", "title": "Like You", "hints": ["Chris Brown", "Mario", "B2K", "Omarion"] },
        { "artist": "R. Kelly", "title": "I Believe I Can Fly", "hints": ["Boyz II Men", "Joe", "Ginuwine", "Tyrese"] },
        { "artist": "Nelly", "title": "Hot In Herre", "hints": ["Ludacris", "Busta Rhymes", "Jay-Z", "Cassidy"] },
        { "artist": "Diana King", "title": "Shy Guy", "hints": ["Lauryn Hill", "Mýa", "Brandy", "Monica"] },
        { "artist": "Pharrell Williams", "title": "Frontin'", "hints": ["Jay-Z", "Nelly", "Ludacris", "Busta Rhymes"] },
        { "artist": "Mariah Carey", "title": "Hero", "hints": ["Whitney Houston", "Toni Braxton", "Mary J. Blige", "Alicia Keys"] },
        { "artist": "TLC", "title": "Waterfalls", "hints": ["Destiny's Child", "Brandy", "SWV", "En Vogue"] },
        { "artist": "Big Punisher", "title": "Still Not a Player", "hints": ["Jay-Z", "Nelly", "Busta Rhymes", "Ludacris"] },
        { "artist": "Toni Braxton", "title": "Un-break My Heart", "hints": ["Whitney Houston", "Mariah Carey", "Mary J. Blige", "Brandy"] },
        { "artist": "Next", "title": "Too Close", "hints": ["Boyz II Men", "Blackstreet", "Ginuwine", "Joe"] },
        { "artist": "Ashanti", "title": "Foolish", "hints": ["Mýa", "Amerie", "Ciara", "Brandy"] },
        { "artist": "Boyz II Men", "title": "I'll Make Love to You", "hints": ["Blackstreet", "Next", "Ginuwine", "Joe"] },
        { "artist": "Erick Sermon", "title": "Music", "hints": ["Jay-Z", "Nelly", "Ludacris", "Busta Rhymes"] }
    ],
    'clubdorothee': [
        { brand: 'Dragon Ball', artist: 'Ariane Carletti', title: 'Dragon Ball', hints: ['Dragon Ball', 'Dragon Ball Z', 'Olive et Tom', 'Nicky Larson'] },
        { brand: 'Dragon Ball Z', artist: 'Ariane Carletti', title: 'Dragon Ball Z', hints: ['Dragon Ball Z', 'Dragon Ball', 'Les Chevaliers du Zodiaque', 'Bioman'] },
        { brand: 'Les Chevaliers du Zodiaque', artist: 'Bernard Minet', title: 'Les Chevaliers du Zodiaque', hints: ['Les Chevaliers du Zodiaque', 'Bioman', 'Sailor Moon', 'Nicky Larson'] },
        { brand: 'Olive et Tom', artist: 'Jean-Claude Corbel', title: 'Olive et Tom', hints: ['Olive et Tom', 'Jeanne et Serge', 'Dragon Ball', 'Lucile Amour et Rock\'n Roll'] },
        { brand: 'Jeanne et Serge', artist: 'Claude Lombard', title: 'Jeanne et Serge', hints: ['Jeanne et Serge', 'Olive et Tom', 'Juliette je t\'aime', 'Max et Compagnie'] },
        { brand: 'Nicky Larson', artist: 'Jean-Paul Césari', title: 'Nicky Larson', hints: ['Nicky Larson', 'Cat\'s Eyes', 'Signé Cat\'s Eyes', 'Cobra'] },
        { brand: 'Bioman', artist: 'Bernard Minet', title: 'Bioman', hints: ['Bioman', 'X-Or', 'Les Chevaliers du Zodiaque', 'Mask'] },
        { brand: 'Inspecteur Gadget', artist: 'Jacques Cardona', title: 'Inspecteur Gadget', hints: ['Inspecteur Gadget', 'Ulysse 31', 'Les Mystérieuses Cités d\'Or', 'Denver le dernier dinosaure'] },
        { brand: 'Sailor Moon', artist: 'Bernard Minet', title: 'Sailor Moon', hints: ['Sailor Moon', 'Cardcaptor Sakura', 'Lucile Amour et Rock\'n Roll', 'Gigi'] },
        { brand: 'Denver le dernier dinosaure', artist: 'Carlos Lipesker', title: 'Denver le dernier dinosaure', hints: ['Denver le dernier dinosaure', 'Inspecteur Gadget', 'Les Tortues Ninja', 'Les Snorky'] },
        { brand: 'Les Mystérieuses Cités d\'Or', artist: 'Jacques Cardona', title: 'Les Mystérieuses Cités d\'Or', hints: ['Les Mystérieuses Cités d\'Or', 'Ulysse 31', 'Tom Sawyer', 'Rémi sans famille'] },
        { brand: 'Signé Cat\'s Eyes', artist: 'Isabelle Ganot', title: 'Signé Cat\'s Eyes', hints: ['Signé Cat\'s Eyes', 'Nicky Larson', 'Juliette je t\'aime', 'Cobra'] },
        { brand: 'Princesse Sarah', artist: 'Cristina D\'Avena', title: 'Princesse Sarah', hints: ['Princesse Sarah', 'Heidi', 'Candy', 'Pollyanna'] },
        { brand: 'Juliette je t\'aime', artist: 'Isabelle Ganot', title: 'Juliette je t\'aime', hints: ['Juliette je t\'aime', 'Lucile Amour et Rock\'n Roll', 'Max et Compagnie', 'Signé Cat\'s Eyes'] },
        { brand: 'Lucile Amour et Rock\'n Roll', artist: 'Isabelle Ganot', title: 'Lucile Amour et Rock\'n Roll', hints: ['Lucile Amour et Rock\'n Roll', 'Juliette je t\'aime', 'Max et Compagnie', 'Creamy'] },
        { brand: 'Max et Compagnie', artist: 'Claude Lombard', title: 'Max et Compagnie', hints: ['Max et Compagnie', 'Lucile Amour et Rock\'n Roll', 'Juliette je t\'aime', 'Théo ou la Batte de la Victoire'] },
        { brand: 'Cat\'s Eyes', artist: 'Isabelle Ganot', title: 'Signé Cat\'s Eyes', hints: ['Cat\'s Eyes', 'Nicky Larson', 'Cobra', 'Sherlock Holmes'] },
        { brand: 'Transformers', artist: 'Bernard Minet', title: 'Transformers pour un monde meilleur', hints: ['Transformers', 'MASK', 'GI Joe', 'GoBots'] },
        { brand: 'MASK', artist: 'Noam Kaniel', title: 'MASK', hints: ['MASK', 'Transformers', 'Jayce et les Conquérants de la Lumière', 'GI Joe'] }
    ],
    'toushits': [
        { "artist": "Daft Punk", "title": "Get Lucky", "hints": [] },
        { "artist": "Pharrell Williams", "title": "Happy", "hints": [] },
        { "artist": "Ed Sheeran", "title": "Shape of You", "hints": [] },
        { "artist": "Rihanna", "title": "Umbrella", "hints": [] },
        { "artist": "Justin Timberlake", "title": "Can't Stop the Feeling!", "hints": [] },
        { "artist": "The Weeknd", "title": "Blinding Lights", "hints": [] },
        { "artist": "Dua Lipa", "title": "Levitating", "hints": [] },
        { "artist": "Harry Styles", "title": "As It Was", "hints": [] },
        { "artist": "Taylor Swift", "title": "Shake It Off", "hints": [] },
        { "artist": "Bruno Mars", "title": "Uptown Funk", "hints": [] },
        { "artist": "Beyoncé", "title": "Single Ladies", "hints": [] },
        { "artist": "Lady Gaga", "title": "Bad Romance", "hints": [] },
        { "artist": "Adele", "title": "Rolling in the Deep", "hints": [] },
        { "artist": "Coldplay", "title": "Viva La Vida", "hints": [] },
        { "artist": "Billie Eilish", "title": "Bad Guy", "hints": [] },
        { "artist": "Sia", "title": "Chandelier", "hints": [] },
        { "artist": "Miley Cyrus", "title": "Flowers", "hints": [] },
        { "artist": "Imagine Dragons", "title": "Believer", "hints": [] },
        { "artist": "Stromae", "title": "Alors on danse", "hints": [] },
        { "artist": "Angèle", "title": "Balance ton quoi", "hints": [] },
        { "artist": "Orelsan", "title": "La Terre est ronde", "hints": [] },
        { "artist": "Soprano", "title": "En feu", "hints": [] },
        { "artist": "Gims", "title": "Sapés comme jamais", "hints": [] },
        { "artist": "David Guetta", "title": "Titanium", "hints": [] }
    ],
    'series': [
        { brand: 'Friends', artist: 'The Rembrandts', title: 'I\'ll Be There For You', hints: ['Friends', 'How I Met Your Mother', 'The Big Bang Theory', 'Scrubs'] },
        { brand: 'X-Files', artist: 'Mark Snow', title: 'The X-Files Theme', hints: ['X-Files', 'Fringe', 'Supernatural', 'Twin Peaks'] },
        { brand: 'Prison Break', artist: 'Faf Larage', title: 'Pas le temps', hints: ['Prison Break', 'Lost', '24 Heures Chrono', 'Dexter'] },
        { brand: 'Charmed', artist: 'Love Spit Love', title: 'How Soon Is Now?', hints: ['Charmed', 'Buffy contre les vampires', 'Sabrina l\'apprentie sorcière', 'Ghost Whisperer'] },
        { brand: 'Game of Thrones', artist: 'Ramin Djawadi', title: 'Main Title', hints: ['Game of Thrones', 'Le Seigneur des Anneaux', 'The Witcher', 'Vikings'] },
        { brand: 'Les Frères Scott', artist: 'Gavin DeGraw', title: 'I Don\'t Want to Be', hints: ['Les Frères Scott', 'Newport Beach', 'Dawson', 'Gossip Girl'] },
        { brand: 'Malcolm', artist: 'They Might Be Giants', title: 'Boss of Me', hints: ['Malcolm', 'Ma Famille d\'Abord', 'Scrubs', 'The Middle'] },
        { brand: 'Stranger Things', artist: 'Kyle Dixon', title: 'Stranger Things', hints: ['Stranger Things', 'Dark', 'The OA', 'Black Mirror'] },
        { brand: 'La Casa de Papel', artist: 'Cecilia Krull', title: 'My Life Is Going On', hints: ['La Casa de Papel', 'Narcos', 'Elite', 'Lupin'] },
        { brand: 'Le Prince de Bel-Air', artist: 'DJ Jazzy Jeff', title: 'The Fresh Prince of Bel-Air', hints: ['Le Prince de Bel-Air', 'Ma Famille d\'Abord', 'Cosby Show', 'Kenan et Kel'] },
        { brand: 'Alerte à Malibu', artist: 'Jimi Jamison', title: 'I\'m Always Here', hints: ['Alerte à Malibu', 'Magnum', 'K2000', 'MacGyver'] },
        { brand: 'MacGyver', artist: 'Randy Edelman', title: 'MacGyver Theme', hints: ['MacGyver', 'L\'Agence Tous Risques', 'K2000', 'Magnum'] }
    ],
    'movies': [
        { brand: 'Titanic', artist: 'Celine Dion', title: 'My Heart Will Go On' },
        { brand: 'Star Wars', artist: 'John Williams', title: 'Main Theme' },
        { brand: 'James Bond', artist: 'Adele', title: 'Skyfall' },
        { brand: 'Rocky', artist: 'Survivor', title: 'Eye of the Tiger' },
        { brand: 'Grease', artist: 'John Travolta', title: 'You\'re The One That I Want' },
        { brand: 'Ghostbusters', artist: 'Ray Parker Jr', title: 'Ghostbusters' },
        { brand: 'Pulp Fiction', artist: 'Dick Dale', title: 'Misirlou' },
        { brand: 'Mission Impossible', artist: 'Lalo Schifrin', title: 'Theme from Mission: Impossible' },
        { brand: 'Harry Potter', artist: 'John Williams', title: 'Hedwig\'s Theme' },
        { brand: 'Jurassic Park', artist: 'John Williams', title: 'Theme from Jurassic Park' },
        { brand: 'Le Professionnel', artist: 'Ennio Morricone', title: 'Chi Mai' },
        { brand: 'La Boum', artist: 'Richard Sanderson', title: 'Reality' },
        { brand: 'Les Bronzés', artist: 'Pierre Bachelet', title: 'Just Because of You' },
        { brand: 'Retour vers le futur', artist: 'Huey Lewis', title: 'The Power of Love' },
        { brand: 'Dirty Dancing', artist: 'Bill Medley', title: '(I\'ve Had) The Time of My Life' },
        { brand: 'Top Gun', artist: 'Berlin', title: 'Take My Breath Away' },
        { brand: 'Bodyguard', artist: 'Whitney Houston', title: 'I Will Always Love You' },
        { brand: 'Le Flic de Beverly Hills', artist: 'Harold Faltermeyer', title: 'Axel F' },
        { brand: 'Flashdance', artist: 'Irene Cara', title: 'Flashdance... What a Feeling' },
        { brand: 'Le Seigneur des Anneaux', artist: 'Howard Shore', title: 'The Shire' }
    ]
};
