/**
 * DATABASE DES TITRES - STITCH 2026
 */
const SONG_DATABASE = {
    '8090': [
        { "artist": "Indochine", "title": "L’Aventurier", "hints": [] },
        { "artist": "Vanessa Paradis", "title": "Joe le taxi", "hints": [] },
        { "artist": "France Gall", "title": "Ella, elle l’a", "hints": [] },
        { "artist": "Images", "title": "Les démons de minuit", "hints": [] },
        { "artist": "Peter et Sloane", "title": "Besoin de rien, envie de toi", "hints": [] },
        { "artist": "Jeanne Mas", "title": "Toute première fois", "hints": [] },
        { "artist": "Niagara", "title": "L’amour à la plage", "hints": [] },
        { "artist": "Lio", "title": "Amoureux solitaires", "hints": [] },
        { "artist": "Rose Laurens", "title": "Africa", "hints": [] },
        { "artist": "Hervé Cristiani", "title": "Il est libre Max", "hints": [] },
        { "artist": "Axel Bauer", "title": "Cargo", "hints": [] },
        { "artist": "Taxi Girl", "title": "Cherchez le garçon", "hints": [] },
        { "artist": "Rita Mitsouko", "title": "Marcia Baïla", "hints": [] },
        { "artist": "Partenaire Particulier", "title": "Partenaire particulier", "hints": [] },
        { "artist": "Jean-Jacques Goldman", "title": "Envole-moi", "hints": [] },
        { "artist": "Jean-Jacques Goldman", "title": "Je te donne", "hints": [] },
        { "artist": "Fredericks Goldman Jones", "title": "À nos actes manqués", "hints": [] },
        { "artist": "Téléphone", "title": "Cendrillon", "hints": [] },
        { "artist": "Téléphone", "title": "Ça (c’est vraiment toi)", "hints": [] },
        { "artist": "Bandolero", "title": "Paris Latino", "hints": [] },
        { "artist": "Jean Schultheis", "title": "Confidence pour confidence", "hints": [] },
        { "artist": "Thierry Pastor", "title": "Le coup de folie", "hints": [] },
        { "artist": "Jean-Luc Lahaye", "title": "Femme que j’aime", "hints": [] },
        { "artist": "François Valéry", "title": "Aimons-nous vivants", "hints": [] },
        { "artist": "Philippe Cataldo", "title": "Les Divas du dancing", "hints": [] },
        { "artist": "Les Avions", "title": "Nuit sauvage", "hints": [] },
        { "artist": "Jakie Quartz", "title": "Mise au point", "hints": [] },
        { "artist": "Caroline Loeb", "title": "C’est la ouate", "hints": [] },
        { "artist": "Jacques Higelin", "title": "Tombé du ciel", "hints": [] },
        { "artist": "Mylène Farmer", "title": "Désenchantée", "hints": [] },
        { "artist": "Céline Dion", "title": "Pour que tu m’aimes encore", "hints": [] },
        { "artist": "Céline Dion & Jean-Jacques Goldman", "title": "J’irai où tu iras", "hints": [] },
        { "artist": "Fredericks Goldman Jones", "title": "À nos actes manqués", "hints": [] },
        { "artist": "Fredericks Goldman Jones", "title": "Né en 17 à Leidenstadt", "hints": [] },
        { "artist": "MC Solaar", "title": "Caroline", "hints": [] },
        { "artist": "MC Solaar", "title": "Bouge de là", "hints": [] },
        { "artist": "IAM", "title": "Je danse le mia", "hints": [] },
        { "artist": "Zebda", "title": "Tomber la chemise", "hints": [] },
        { "artist": "Tina Arena", "title": "Aller plus haut", "hints": [] },
        { "artist": "Pauline Ester", "title": "Oui je l’adore", "hints": [] },
        { "artist": "Roch Voisine", "title": "Hélène", "hints": [] },
        { "artist": "Roch Voisine", "title": "Pourtant", "hints": [] },
        { "artist": "Didier Barbelivien & Félix Gray", "title": "À toutes les filles", "hints": [] },
        { "artist": "Demis Roussos", "title": "On écrit sur les murs", "hints": [] },
        { "artist": "Johnny Hallyday", "title": "Je te promets", "hints": [] },
        { "artist": "Lagaf’", "title": "La zoubida", "hints": [] },
        { "artist": "Zouk Machine", "title": "Maldòn (la musique dans la peau)", "hints": [] },
        { "artist": "Pascal Obispo", "title": "Tomber pour elle", "hints": [] },
        { "artist": "Alain Souchon", "title": "Sous les jupes des filles", "hints": [] },
        { "artist": "Alain Bashung", "title": "Madame rêve", "hints": [] },
        { "artist": "Niagara", "title": "J’ai vu", "hints": [] },
        { "artist": "Laurent Voulzy", "title": "Les nuits sans Kim Wilde", "hints": [] },
        { "artist": "Axel Bauer", "title": "Éteins la lumière", "hints": [] },
        { "artist": "François Feldman", "title": "Les valses de Vienne", "hints": [] },
        { "artist": "Teri Moïse", "title": "Je serai là", "hints": [] },
        { "artist": "Mylène Farmer", "title": "Tomber...", "hints": [] },
        { "artist": "Hélène", "title": "Hélène et les garçons", "hints": [] },
        { "artist": "Marc Lavoine", "title": "Tomber la nuit", "hints": [] }
    ],
    // ... rest of DB deleted for brevity in this tool call but I'll provide the full one in real call
};
